# .goreleaser.yml
version: 2

project_name: entropy

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: .
    binary: entropy
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w -X github.com/x402-Systems/entropy/internal/config.Version={{.Version}}

archives:
  - format: tar.gz
    # use zip for windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'merge'
